version: '3'
services:
  backend:
    environment:
      - DB_URL=postgres://user:password@db:5432/Playlist?sslmode=disable
    build: .
    ports:
      - "8888:8888"
      - "5536:5536"
    networks:
      - mynetwork
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Playlist
      - PG_SSLMODE=disable
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./internal/database/postgres/sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "max_prepared_transactions=0"]

volumes:
  db_data:
networks:
  mynetwork: